FROM php:8.2-apache

RUN apt-get update && apt-get install -y \
    libsqlite3-dev unzip git \
    && docker-php-ext-install pdo pdo_sqlite \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN a2enmod rewrite

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html
COPY . .

RUN cp apache.conf /etc/apache2/sites-available/000-default.conf

RUN composer install --no-interaction --optimize-autoloader --no-dev --ignore-platform-req=ext-zip

RUN touch database/database.sqlite \
    && chown -R www-data:www-data /var/www/html \
    && chmod -R 775 storage bootstrap/cache database

EXPOSE 80

CMD ["sh", "-c", "php artisan config:clear && php artisan migrate:fresh --seed --force && apache2-foreground"]