<?php

namespace Database\Seeders;

use App\Models\Activity;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Create admin user
        $admin = User::create([
            'name'       => 'System Admin',
            'email'      => 'admin@npontu.com',
            'password'   => Hash::make('password'),
            'role'       => 'admin',
            'department' => 'IT',
            'phone'      => '+233 55 654 1525',
        ]);

        // Create sample staff
        $staff = User::create([
            'name'       => 'Kofi Mensah',
            'email'      => 'kofi@npontu.com',
            'password'   => Hash::make('password'),
            'role'       => 'staff',
            'department' => 'Applications Support',
            'phone'      => '+233 24 337 5520',
        ]);

        // Seed default daily activities
        $activities = [
            ['title' => 'Daily SMS Count vs Log Count', 'description' => 'Compare the daily SMS count generated by the application against the count from system logs to detect discrepancies.', 'category' => 'Monitoring', 'priority' => 'high'],
            ['title' => 'Application Error Log Review', 'description' => 'Review and categorise all application error logs generated during the previous 24 hours.', 'category' => 'Monitoring', 'priority' => 'high'],
            ['title' => 'Database Backup Verification', 'description' => 'Confirm that automated database backups completed successfully and are accessible.', 'category' => 'Maintenance', 'priority' => 'high'],
            ['title' => 'Server Uptime Check', 'description' => 'Verify server uptime metrics and ensure all critical services are running.', 'category' => 'Monitoring', 'priority' => 'medium'],
            ['title' => 'Pending Tickets Review', 'description' => 'Review all open support tickets and update their status or escalate as required.', 'category' => 'Support', 'priority' => 'medium'],
            ['title' => 'System Performance Metrics', 'description' => 'Record CPU, memory and disk usage metrics from the monitoring dashboard.', 'category' => 'Monitoring', 'priority' => 'medium'],
            ['title' => 'End-of-Day Handover Report', 'description' => 'Prepare and submit the handover report for the incoming shift, listing all pending activities.', 'category' => 'Reporting', 'priority' => 'high'],
        ];

        foreach ($activities as $data) {
            Activity::create(array_merge($data, ['created_by' => $admin->id]));
        }
    }
}
