services:
  - type: web
    name: team-tracker
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache
    startCommand: php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_KEY
        value: base64:LqARTY7F2IzylnDrJWgmjaSZrA9ES7EhshytOWTxJ7k=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/data/database.sqlite